### PR TITLE
Fix cpp graphql schema generation including variants

### LINKED ISSUE #966: producers gql invalid schema
`ConsensusData` is printed in the schema twice for some reason

```
type Claim {
    service: String!
    rawData: [Int!]!
}
type Producer {
    name: String!
    auth: Claim!
}
type CftConsensus {
    producers: [Producer!]!
}
type BftConsensus {
    producers: [Producer!]!
}
union ConsensusData =
  | CftConsensus
  | BftConsensus
union ConsensusData =
  | CftConsensus
  | BftConsensus
type Query {
    producers: [Producer!]!
    nextProducers: [Producer!]!
    consensus: ConsensusData!
    nextConsensus: ConsensusData
    jointStart: Float
}
```

### PR DESCRIPTION
**Pull request by James-Mart**
Closes #966

### CODE REVIEW

File: libraries/psio/include/psio/graphql.hpp [hunk 1]
```diff
@@ -359,13 +359,16 @@ namespace psio
                              bool                                        is_query_root)
    {
       (fill_gql_schema((T*)nullptr, stream, defined_types, is_input, false), ...);
```
Comment (swatanabe) [inline libraries/psio/include/psio/graphql.hpp:361]: This should probably be inside the condition.  It could cause infinite recursion in some corner cases.

Comment (James-Mart) [reply libraries/psio/include/psio/graphql.hpp]: Fixed

**Review by swatanabe — APPROVED** [review]
